baseURL = ""
languageCode = "en-US"
defaultContentLanguage = "en"

title = "CloudBees CI Workshop"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "cloudbees"
  editURL = "https://github.com/cloudbees-days/cloudbees-field-workshops/edit/main/labs/cloudbees-ci/content/"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true